name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  cross:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0

    strategy:
      matrix:
        go-version: [ stable, oldstable ]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -ldflags "-s -w" -trimpath ./cmd/nilerr/

      - name: Test
        run: go test -v -cover ./...

  inception:
    name: Inception
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6

      - name: Install
        run: go install -ldflags "-s -w" -trimpath ./cmd/nilerr/

      - name: Run
        run: go vet -vettool=$(go env GOPATH)/bin/nilerr ./...
